name: Maven Build
on: [push]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish JUnit Test Report
        if: always()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: target/surefire-reports/TEST-*.xml
          detailed_summary: true
          include_passed: true
          check_title_template: "{{SUITE_NAME}}/{{TEST_NAME}}"